// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzfjqckcrlywnzeqkurp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZmpxY2tjcmx5d256ZXFrdXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTY1NTAsImV4cCI6MjA2NjI3MjU1MH0.z4xXHE5rk0bxpiMh9i09BghtEs5yMoUrc-jZNhZC2EQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);